### ISSUE TITLE
Add note about 'impedance matching' ActiveModeAdapter to Rails's Active Model Serializers

### ISSUE THREAD

**Issue by GA-MEB** [ga-wdi-boston/ember-data-associations#11]
Serializing child records in Rails and using DS relationship attributes (e.g. `DS.hasMany` or `DS.belongsTo`) causes an error with the store:

![screen shot 2016-04-07 at 6 15 58 pm](https://cloud.githubusercontent.com/assets/16352837/14368624/e8ca11d8-fcec-11e5-94c4-365d6ec7d042.png)

https://github.com/ember-data/active-model-adapter

This can be solved in one of two ways:
1. Don't serialize the child record associations at all - just expose foreign keys for parent records. Then, you can use  `DS.hasMany` /  `DS.belongsTo`.
2. Define relationships on the front end as empty arrays using `DS.attr()` and write methods in the Rails Serializers to pluck out ids of associated records and embed them during serialization, producing something that looks like this:

``` json
{ 
  "parent":  {
    "property1": "blah",
    "property2": "blah",
    "children" : [ 1, 3, 4, 5 ]
  } 
}
```

Not really sure which solution is the "right" one, since both seem to work, but there may be hidden disadvantages to the first approach (possibly that it might make model loading more complicated?).

**Comment by jrhorn424** [comment]
We currently handle this with custom serializers in the API, and have been talking about moving to JSON API in the future, assuming we can find a plugin to handle formatting responses for express.
