### ISSUE TITLE
Remove other associations and put in their own repos

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/ember-data-associations#7]
This is `ember-resources-one-to-many`. Other repos will be:
- `ember-resources-one-to-one`
- `ember-resources-many-to-many`

**Comment by GA-MEB** [comment]
Partly done. Old content has been removed from this repo, but new repos need to be created.

**Comment by jrhorn424** [comment]
This repository should move into deprecation.

As a side note, @GA-MEB, your scaffolding of one umbrella `resources` repository is what we've been using for three or so instances now. Good intuition.
